// Generated by scripts/generate-sample.js then hand-edited for demo polish.
// Source of truth: samples/demo-extraction.json — keep in sync.
export const SAMPLE_PROJECT = {
  "id": "sample-demo-001",
  "name": "Sample: Structural Framing (S1)",
  "pdf_filename": "s1-framing.pdf",
  "total_pages": 1,
  "created_at": "2026-05-20T04:00:38.964Z",
  "summary": {
    "total": 8,
    "done": 0,
    "flagged": 2,
    "pending": 6,
    "in_progress": 0
  }
}

export const SAMPLE_ITEMS = [
  {
    "id": "MK-001",
    "markup_text": "JOIST BEARING AT EXT. WALL NOT SHOWN — ADD DTL",
    "markup_type": "add",
    "drawing_reference": "S4.20",
    "location_on_drawing": "Left side of drawing, pointing to exterior wall area",
    "related_to": null,
    "confidence": "high",
    "ambiguous": false,
    "page_number": 1,
    "status": "pending",
    "flagged": false,
    "clarification_request": null
  },
  {
    "id": "MK-003",
    "markup_text": "CONN. DETAIL MISSING AT RIDGE BEAM TO ADDL — ADD REF.",
    "markup_type": "add",
    "drawing_reference": "S4.20",
    "location_on_drawing": "Upper center area at ridge beam connection",
    "related_to": null,
    "confidence": "high",
    "ambiguous": false,
    "page_number": 1,
    "status": "pending",
    "flagged": false,
    "clarification_request": null
  },
  {
    "id": "MK-005",
    "markup_text": "W12x26 UNDERSIZED FOR 26' SPAN — INCL. REF'S W16x31",
    "markup_type": "modify",
    "drawing_reference": "S4.20",
    "location_on_drawing": "Center-left area with beam sizing annotation",
    "related_to": null,
    "confidence": "high",
    "ambiguous": false,
    "page_number": 1,
    "status": "pending",
    "flagged": false,
    "clarification_request": null
  },
  {
    "id": "MK-007",
    "markup_text": "HIP RAFTER SIZE NOT CALLED OUT — ADD MEMBER SIZE",
    "markup_type": "add",
    "drawing_reference": "S4.20",
    "location_on_drawing": "Right side of drawing at hip rafter location",
    "related_to": null,
    "confidence": "high",
    "ambiguous": false,
    "page_number": 1,
    "status": "pending",
    "flagged": false,
    "clarification_request": null
  },
  {
    "id": "MK-009",
    "markup_text": "MIDSPAN BLOCKING MISSING — REQ'D FOR LATERAL STABILITY",
    "markup_type": "add",
    "drawing_reference": "S4.20",
    "location_on_drawing": "Center area of framing plan indicating missing blocking",
    "related_to": null,
    "confidence": "high",
    "ambiguous": false,
    "page_number": 1,
    "status": "pending",
    "flagged": false,
    "clarification_request": null
  },
  {
    "id": "MK-010",
    "markup_text": "LEDGER ATTACH. DETAIL MISSING — ADD W/ BOLT PATTERN",
    "markup_type": "add",
    "drawing_reference": "S4.20",
    "location_on_drawing": "Lower left area with red cloud highlighting ledger attachment location",
    "related_to": null,
    "confidence": "high",
    "ambiguous": false,
    "page_number": 1,
    "status": "pending",
    "flagged": false,
    "clarification_request": null
  },
  {
    "id": "MK-011",
    "markup_text": "verify?",
    "markup_type": "clarify",
    "drawing_reference": "S4.20",
    "location_on_drawing": "Lower-left area near W12x14 beam, red oval around member size",
    "related_to": null,
    "confidence": "low",
    "ambiguous": true,
    "page_number": 1,
    "status": "flagged",
    "flagged": true,
    "clarification_request": null
  },
  {
    "id": "MK-012",
    "markup_text": "??",
    "markup_type": "clarify",
    "drawing_reference": "S4.20",
    "location_on_drawing": "Upper-right area near W12x19 beam, red double question mark with circle",
    "related_to": null,
    "confidence": "low",
    "ambiguous": true,
    "page_number": 1,
    "status": "flagged",
    "flagged": true,
    "clarification_request": null
  }
]
