export const SAMPLE_PROJECT = {
  id: 'sample-demo-001',
  name: 'Sample: Demo Plan',
  pdf_filename: 'demo-plan.pdf',
  total_pages: 1,
}

export const SAMPLE_ITEMS = [
  { id:'MK-001', markup_text:'Spray paint + high paint = black all white', markup_type:'note', drawing_reference:'BATH 01 - E', location_on_drawing:'Upper portion of drawing, curved line connecting to ceiling area', related_to:'MK-002', confidence:'medium', ambiguous:false, page_number:1, status:'pending', flagged:false, clarification_request:null },
  { id:'MK-002', markup_text:'Cloud markup covering ceiling/upper wall area', markup_type:'modify', drawing_reference:'BATH 01 - E', location_on_drawing:'Large curved cloud marking covering the ceiling and upper wall area of both vanity sections', related_to:'MK-001', confidence:'high', ambiguous:false, page_number:1, status:'pending', flagged:false, clarification_request:null },
  { id:'MK-003', markup_text:'-9 1/2', markup_type:'dimension', drawing_reference:'BATH 01 - E', location_on_drawing:'Left side of drawing, vertical dimension line', related_to:null, confidence:'high', ambiguous:false, page_number:1, status:'pending', flagged:false, clarification_request:null },
  { id:'MK-004', markup_text:"6'×0", markup_type:'dimension', drawing_reference:'BATH 01 - E', location_on_drawing:'Center area above the door opening', related_to:null, confidence:'high', ambiguous:false, page_number:1, status:'pending', flagged:false, clarification_request:null },
  { id:'MK-005', markup_text:'X', markup_type:'delete', drawing_reference:'BATH 01 - E', location_on_drawing:'Multiple X marks across the upper portion of both mirror areas', related_to:null, confidence:'high', ambiguous:false, page_number:1, status:'pending', flagged:false, clarification_request:null },
  { id:'MK-006', markup_text:'Hatched area on left mirror', markup_type:'modify', drawing_reference:'BATH 01 - E', location_on_drawing:'Left mirror area with diagonal hatching pattern', related_to:'MK-007', confidence:'high', ambiguous:false, page_number:1, status:'pending', flagged:false, clarification_request:null },
  { id:'MK-007', markup_text:'change local brand of laminate', markup_type:'note', drawing_reference:'BATH 01 - E', location_on_drawing:'Arrow pointing to left mirror area with hatching', related_to:'MK-006', confidence:'medium', ambiguous:false, page_number:1, status:'pending', flagged:false, clarification_request:null },
  { id:'MK-008', markup_text:'Hatched area on right mirror', markup_type:'modify', drawing_reference:'BATH 01 - E', location_on_drawing:'Right mirror area with diagonal hatching pattern', related_to:null, confidence:'high', ambiguous:false, page_number:1, status:'pending', flagged:false, clarification_request:null },
  { id:'MK-009', markup_text:'Turn U', markup_type:'note', drawing_reference:'BATH 01 - E', location_on_drawing:'Left side of drawing, near the vanity base', related_to:null, confidence:'medium', ambiguous:true, page_number:1, status:'flagged', flagged:true, clarification_request:'Auto-flagged: markup intent is unclear. Confidence: medium' },
  { id:'MK-010', markup_text:'Hatched area on left vanity base', markup_type:'modify', drawing_reference:'BATH 01 - E', location_on_drawing:'Left vanity base cabinet with diagonal hatching', related_to:null, confidence:'high', ambiguous:false, page_number:1, status:'pending', flagged:false, clarification_request:null },
  { id:'MK-011', markup_text:'Hatched area on right vanity base', markup_type:'modify', drawing_reference:'BATH 01 - E', location_on_drawing:'Right vanity base cabinet with diagonal hatching', related_to:null, confidence:'high', ambiguous:false, page_number:1, status:'pending', flagged:false, clarification_request:null },
  { id:'MK-012', markup_text:'Circled dimension 1 1/2', markup_type:'dimension', drawing_reference:'BATH 01 - E', location_on_drawing:'Bottom left of drawing, circled dimension', related_to:null, confidence:'high', ambiguous:false, page_number:1, status:'pending', flagged:false, clarification_request:null },
  { id:'MK-013', markup_text:'1/2"', markup_type:'dimension', drawing_reference:'BATH 01 - E', location_on_drawing:'Below drawing, first dimension notation', related_to:null, confidence:'high', ambiguous:false, page_number:1, status:'pending', flagged:false, clarification_request:null },
  { id:'MK-014', markup_text:'1 1/2"', markup_type:'dimension', drawing_reference:'BATH 01 - E', location_on_drawing:'Below drawing, second dimension notation', related_to:null, confidence:'high', ambiguous:false, page_number:1, status:'pending', flagged:false, clarification_request:null },
  { id:'MK-015', markup_text:'1/2"', markup_type:'dimension', drawing_reference:'BATH 01 - E', location_on_drawing:'Below drawing, third dimension notation', related_to:null, confidence:'high', ambiguous:false, page_number:1, status:'pending', flagged:false, clarification_request:null },
  { id:'MK-016', markup_text:'1/2"', markup_type:'dimension', drawing_reference:'BATH 01 - E', location_on_drawing:'Below drawing, fourth dimension notation', related_to:null, confidence:'high', ambiguous:false, page_number:1, status:'pending', flagged:false, clarification_request:null },
  { id:'MK-017', markup_text:'Circled dimension on right side', markup_type:'dimension', drawing_reference:'BATH 01 - E', location_on_drawing:'Bottom right of drawing, circled dimension', related_to:null, confidence:'medium', ambiguous:false, page_number:1, status:'pending', flagged:false, clarification_request:null },
  { id:'MK-018', markup_text:'Hit is soaking', markup_type:'note', drawing_reference:'BATH 01 - E', location_on_drawing:'Bottom left corner below the drawing', related_to:null, confidence:'low', ambiguous:true, page_number:1, status:'flagged', flagged:true, clarification_request:'Auto-flagged: markup intent is unclear. Confidence: low' },
  { id:'MK-019', markup_text:'Arching penned w/ 4%', markup_type:'note', drawing_reference:'BATH 01 - E', location_on_drawing:'Bottom left corner below the drawing, second line of text', related_to:null, confidence:'low', ambiguous:true, page_number:1, status:'flagged', flagged:true, clarification_request:'Auto-flagged: markup intent is unclear. Confidence: low' },
]
